name: Semantic pull request

on:
  pull_request_target:
    types:
      - edited
      - opened
      - synchronize

jobs:
  main:
    permissions:
      pull-requests: read
      statuses: write

    runs-on: ubuntu-latest

    steps:
      - name: 🔬 Lint pull request title
        uses: amannn/action-semantic-pull-request@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
